# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(379, 354)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SettingDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_cam_setting = QtWidgets.QWidget()
        self.tab_cam_setting.setObjectName("tab_cam_setting")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_cam_setting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formerIntCheckBox = QtWidgets.QCheckBox(self.tab_cam_setting)
        self.formerIntCheckBox.setObjectName("formerIntCheckBox")
        self.verticalLayout.addWidget(self.formerIntCheckBox)
        self.camSeqCheckBox = QtWidgets.QCheckBox(self.tab_cam_setting)
        self.camSeqCheckBox.setObjectName("camSeqCheckBox")
        self.verticalLayout.addWidget(self.camSeqCheckBox)
        self.camDelayCheckBox = QtWidgets.QCheckBox(self.tab_cam_setting)
        self.camDelayCheckBox.setObjectName("camDelayCheckBox")
        self.verticalLayout.addWidget(self.camDelayCheckBox)
        self.sensorCheckBox = QtWidgets.QCheckBox(self.tab_cam_setting)
        self.sensorCheckBox.setObjectName("sensorCheckBox")
        self.verticalLayout.addWidget(self.sensorCheckBox)
        self.rasmOffsetCheckBox = QtWidgets.QCheckBox(self.tab_cam_setting)
        self.rasmOffsetCheckBox.setObjectName("rasmOffsetCheckBox")
        self.verticalLayout.addWidget(self.rasmOffsetCheckBox)
        spacerItem = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_cam_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 20))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.grid_sensor = QtWidgets.QGridLayout()
        self.grid_sensor.setContentsMargins(4, 4, 4, 4)
        self.grid_sensor.setObjectName("grid_sensor")
        self.horizontalLayout_6.addLayout(self.grid_sensor)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tab_cam_setting, "")
        self.tab_plc_setting = QtWidgets.QWidget()
        self.tab_plc_setting.setObjectName("tab_plc_setting")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_plc_setting)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_plc_setting)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.form_plc_2 = QtWidgets.QFormLayout()
        self.form_plc_2.setObjectName("form_plc_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.form_plc_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.form_plc_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.form_plc_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.form_plc_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_4.addLayout(self.form_plc_2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_plc_setting)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.form_plc_3 = QtWidgets.QFormLayout()
        self.form_plc_3.setObjectName("form_plc_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.form_plc_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.form_plc_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.form_plc_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.form_plc_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_5.addLayout(self.form_plc_3)
        self.gridLayout.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_plc_setting)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.form_plc_0 = QtWidgets.QFormLayout()
        self.form_plc_0.setObjectName("form_plc_0")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.form_plc_0.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.form_plc_0.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.form_plc_0.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.form_plc_0.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalLayout_2.addLayout(self.form_plc_0)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_plc_setting)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.form_plc_1 = QtWidgets.QFormLayout()
        self.form_plc_1.setObjectName("form_plc_1")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.form_plc_1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.form_plc_1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.form_plc_1.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setObjectName("label_14")
        self.form_plc_1.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_3.addLayout(self.form_plc_1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.tab_plc_setting)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_plc_setting, "")
        self.tab_general_setting = QtWidgets.QWidget()
        self.tab_general_setting.setObjectName("tab_general_setting")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_general_setting)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.form_general = QtWidgets.QFormLayout()
        self.form_general.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.form_general.setObjectName("form_general")
        self.label_17 = QtWidgets.QLabel(self.tab_general_setting)
        self.label_17.setObjectName("label_17")
        self.form_general.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.tab_general_setting)
        self.label_18.setObjectName("label_18")
        self.form_general.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.tab_general_setting)
        self.label_19.setObjectName("label_19")
        self.form_general.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.tab_general_setting)
        self.label_20.setObjectName("label_20")
        self.form_general.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.tab_general_setting)
        self.label_21.setObjectName("label_21")
        self.form_general.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.verticalLayout_2.addLayout(self.form_general)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.frame = QtWidgets.QFrame(self.tab_general_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.grid_classToPurge = QtWidgets.QGridLayout()
        self.grid_classToPurge.setObjectName("grid_classToPurge")
        self.gridLayout_4.addLayout(self.grid_classToPurge, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_general_setting, "")
        self.tab_peri_setting = QtWidgets.QWidget()
        self.tab_peri_setting.setObjectName("tab_peri_setting")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_peri_setting)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.periVLayout = QtWidgets.QVBoxLayout()
        self.periVLayout.setSpacing(2)
        self.periVLayout.setObjectName("periVLayout")
        self.verticalLayout_6.addLayout(self.periVLayout)
        self.tabWidget.addTab(self.tab_peri_setting, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formerVLayout = QtWidgets.QVBoxLayout()
        self.formerVLayout.setObjectName("formerVLayout")
        self.formerMarkingCheckBox = QtWidgets.QCheckBox(self.tab)
        self.formerMarkingCheckBox.setObjectName("formerMarkingCheckBox")
        self.formerVLayout.addWidget(self.formerMarkingCheckBox)
        self.verticalLayout_5.addLayout(self.formerVLayout)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(SettingDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Setting"))
        self.formerIntCheckBox.setText(_translate("SettingDialog", "Allow Former Interval Adjustment"))
        self.camSeqCheckBox.setText(_translate("SettingDialog", "Enable Camera Sequence Edit"))
        self.camDelayCheckBox.setText(_translate("SettingDialog", "Enable Camera Delay Adjustment"))
        self.sensorCheckBox.setText(_translate("SettingDialog", "Allow Camera Sensor Adjustment"))
        self.rasmOffsetCheckBox.setText(_translate("SettingDialog", "Allow RASM Anchor Offset Edit"))
        self.groupBox_7.setTitle(_translate("SettingDialog", "Sensors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_cam_setting), _translate("SettingDialog", "Camera && Sensor"))
        self.groupBox.setTitle(_translate("SettingDialog", "Left Out"))
        self.label_7.setText(_translate("SettingDialog", "Distance :"))
        self.label_8.setText(_translate("SettingDialog", "Time Interval :"))
        self.label_9.setText(_translate("SettingDialog", "Duration :"))
        self.label_15.setText(_translate("SettingDialog", "Delay :"))
        self.groupBox_3.setTitle(_translate("SettingDialog", "Right Out"))
        self.label_10.setText(_translate("SettingDialog", "Distance :"))
        self.label_11.setText(_translate("SettingDialog", "Time Interval :"))
        self.label_12.setText(_translate("SettingDialog", "Duration :"))
        self.label_16.setText(_translate("SettingDialog", "Delay :"))
        self.groupBox_2.setTitle(_translate("SettingDialog", "Left In"))
        self.label.setText(_translate("SettingDialog", "Distance :"))
        self.label_2.setText(_translate("SettingDialog", "Time Interval :"))
        self.label_3.setText(_translate("SettingDialog", "Duration :"))
        self.label_13.setText(_translate("SettingDialog", "Delay :"))
        self.groupBox_4.setTitle(_translate("SettingDialog", "Right In"))
        self.label_4.setText(_translate("SettingDialog", "Distance : "))
        self.label_5.setText(_translate("SettingDialog", "Time Interval :"))
        self.label_6.setText(_translate("SettingDialog", "Duration :"))
        self.label_14.setText(_translate("SettingDialog", "Delay :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plc_setting), _translate("SettingDialog", "Purger"))
        self.label_17.setText(_translate("SettingDialog", "Factory:"))
        self.label_18.setText(_translate("SettingDialog", "Line:"))
        self.label_19.setText(_translate("SettingDialog", "PLC IP Addr:"))
        self.label_20.setText(_translate("SettingDialog", "RASM Arm Num:"))
        self.label_21.setText(_translate("SettingDialog", "Teams Webhook Addr:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_general_setting), _translate("SettingDialog", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_peri_setting), _translate("SettingDialog", "Peripherals"))
        self.formerMarkingCheckBox.setText(_translate("SettingDialog", "Enable Former Marking Signal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingDialog", "Former"))

